package db

import (
	"crypto/rand"
	"encoding/hex"
	"log"
	"omji/config"
	"omji/pkg/models"
	"os"
	"time"

	"golang.org/x/crypto/bcrypt"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var DB *gorm.DB

func InitDB(cfg *config.Config) *gorm.DB {
	dsn := cfg.GetDSN()

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger:                 logger.Default.LogMode(logger.Warn),
		SkipDefaultTransaction: true,
		PrepareStmt:            true,
	})
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		log.Fatalf("Failed to get underlying sql.DB: %v", err)
	}
	sqlDB.SetMaxOpenConns(25)
	sqlDB.SetMaxIdleConns(10)
	sqlDB.SetConnMaxLifetime(5 * time.Minute)
	sqlDB.SetConnMaxIdleTime(2 * time.Minute)

	DB = db
	log.Println("Database connected successfully")
	return db
}

func MigrateDB(db *gorm.DB) {
	if err := models.AutoMigrate(db); err != nil {
		log.Fatalf("Database migration failed: %v", err)
	}
	log.Println("✅ Database migrations completed")

	// Seed initial data
	seedData(db)
}

func seedData(db *gorm.DB) {
	// Create default admin user if none exists
	var adminCount int64
	db.Model(&models.User{}).Where("role = ?", "admin").Count(&adminCount)
	if adminCount == 0 {
		adminPassword := os.Getenv("ADMIN_PASSWORD")
		autoGenerated := false
		if adminPassword == "" {
			// Generate a random 16-char password
			randomBytes := make([]byte, 8)
			if _, err := rand.Read(randomBytes); err != nil {
				log.Fatalf("Failed to generate random admin password: %v", err)
			}
			adminPassword = hex.EncodeToString(randomBytes)
			autoGenerated = true
		}

		hashedPassword, err := bcrypt.GenerateFromPassword([]byte(adminPassword), bcrypt.DefaultCost)
		if err != nil {
			log.Fatalf("Failed to hash admin password: %v", err)
		}

		adminUser := models.User{
			Name:       "Admin",
			Email:      "admin",
			Phone:      "admin",
			Password:   string(hashedPassword),
			Role:       "admin",
			IsVerified: true,
		}

		if err := db.Create(&adminUser).Error; err != nil {
			log.Printf("Failed to create admin user: %v", err)
		} else if autoGenerated {
			log.Printf("✅ Default admin user created (username: admin, password: %s) — change this immediately!", adminPassword)
		} else {
			log.Println("✅ Default admin user created with ADMIN_PASSWORD from env")
		}
	}

	// Create sample stores if none exist
	var count int64
	db.Model(&models.Store{}).Count(&count)
	if count == 0 {
		stores := []models.Store{
			{
				Name:       "McDonald's Balingasag",
				Category:   "restaurant",
				Latitude:   8.4343,
				Longitude:  124.5000,
				Address:    "Main St, Balingasag",
				Phone:      "+63912345678",
				Description: "Fast food restaurant",
				IsVerified: true,
				Rating:     4.5,
			},
			{
				Name:       "SM Grocery",
				Category:   "grocery",
				Latitude:   8.4340,
				Longitude:  124.4995,
				Address:    "Plaza St, Balingasag",
				Phone:      "+63912345679",
				Description: "Grocery store",
				IsVerified: true,
				Rating:     4.7,
			},
			{
				Name:       "Pharmacy Plus",
				Category:   "pharmacy",
				Latitude:   8.4345,
				Longitude:  124.5005,
				Address:    "Medical Ave, Balingasag",
				Phone:      "+63912345680",
				Description: "Medicine and health products",
				IsVerified: true,
				Rating:     4.8,
			},
		}

		for _, store := range stores {
			if err := db.Create(&store).Error; err != nil {
				log.Printf("Failed to create sample store %q: %v", store.Name, err)
			}
		}
		log.Println("✅ Sample stores created")
	}

	// Create sample promos if none exist
	db.Model(&models.Promo{}).Count(&count)
	if count == 0 {
		promos := []models.Promo{
			{
				Code:           "WELCOME50",
				Description:    "50% off on first ride",
				DiscountType:   "percentage",
				DiscountValue:  50,
				MinimumAmount:  100,
				MaxDiscount:    500,
				UsageLimit:     1000,
				ApplicableTo:   "rides",
				IsActive:       true,
			},
			{
				Code:           "DELIVERY2024",
				Description:    "Free delivery on orders above 500",
				DiscountType:   "fixed",
				DiscountValue:  0,
				MinimumAmount:  500,
				UsageLimit:     5000,
				ApplicableTo:   "orders",
				IsActive:       true,
			},
		}

		for _, promo := range promos {
			if err := db.Create(&promo).Error; err != nil {
				log.Printf("Failed to create sample promo %q: %v", promo.Code, err)
			}
		}
		log.Println("✅ Sample promos created")
	}
}

func GetDB() *gorm.DB {
	return DB
}
