package db

import (
	"crypto/rand"
	"encoding/hex"
	"log"
	"log/slog"
	"oneride/config"
	"oneride/pkg/models"
	"os"
	"time"

	"golang.org/x/crypto/bcrypt"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var DB *gorm.DB

func InitDB(cfg *config.Config) *gorm.DB {
	dsn := cfg.GetDSN()

	db, err := gorm.Open(postgres.New(postgres.Config{
		DSN:                  dsn,
		PreferSimpleProtocol: true,
	}), &gorm.Config{
		Logger:                                   logger.Default.LogMode(logger.Warn),
		SkipDefaultTransaction:                    true,
		DisableForeignKeyConstraintWhenMigrating:   true,
	})
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	sqlDB, err := db.DB()
	if err != nil {
		log.Fatalf("Failed to get underlying sql.DB: %v", err)
	}
	sqlDB.SetMaxOpenConns(25)
	sqlDB.SetMaxIdleConns(10)
	sqlDB.SetConnMaxLifetime(5 * time.Minute)
	sqlDB.SetConnMaxIdleTime(2 * time.Minute)

	DB = db
	slog.Info("Database connected successfully")
	return db
}

func MigrateDB(db *gorm.DB) {
	// Log the actual users.id column type for diagnostics
	var colType string
	if err := db.Raw("SELECT data_type FROM information_schema.columns WHERE table_schema = CURRENT_SCHEMA() AND table_name = 'users' AND column_name = 'id'").Scan(&colType).Error; err != nil {
		slog.Info("Could not query users.id type (table may not exist yet)", "error", err)
	} else {
		slog.Info("users.id column type", "type", colType)
	}

	if err := models.AutoMigrate(db); err != nil {
		log.Fatalf("Database migration failed: %v", err)
	}

	// Drop NOT NULL constraints on FK columns that need to be nullable for safe deletion.
	// AutoMigrate won't drop NOT NULL on existing columns, so we do it manually.
	nullableFKs := []string{
		"ALTER TABLE rides ALTER COLUMN user_id DROP NOT NULL",
		"ALTER TABLE deliveries ALTER COLUMN user_id DROP NOT NULL",
		"ALTER TABLE orders ALTER COLUMN user_id DROP NOT NULL",
		"ALTER TABLE orders ALTER COLUMN store_id DROP NOT NULL",
		"ALTER TABLE chat_messages ALTER COLUMN sender_id DROP NOT NULL",
		"ALTER TABLE chat_messages ALTER COLUMN receiver_id DROP NOT NULL",
		"ALTER TABLE wallet_transactions ALTER COLUMN user_id DROP NOT NULL",
		"ALTER TABLE wallet_transactions ALTER COLUMN wallet_id DROP NOT NULL",
		"ALTER TABLE ride_shares ALTER COLUMN driver_id DROP NOT NULL",
	}
	for _, stmt := range nullableFKs {
		if err := db.Exec(stmt).Error; err != nil {
			slog.Warn("Nullable FK migration (may already be applied)", "sql", stmt, "error", err)
		}
	}

	slog.Info("Database migrations completed")

	// Seed initial data
	seedData(db)
}

func seedData(db *gorm.DB) {
	// Create or update default admin user
	adminPassword := os.Getenv("ADMIN_PASSWORD")
	var adminCount int64
	db.Model(&models.User{}).Where("role = ?", "admin").Count(&adminCount)
	if adminCount == 0 {
		autoGenerated := false
		if adminPassword == "" {
			// Generate a random 16-char password
			randomBytes := make([]byte, 8)
			if _, err := rand.Read(randomBytes); err != nil {
				log.Fatalf("Failed to generate random admin password: %v", err)
			}
			adminPassword = hex.EncodeToString(randomBytes)
			autoGenerated = true
		}

		hashedPassword, err := bcrypt.GenerateFromPassword([]byte(adminPassword), bcrypt.DefaultCost)
		if err != nil {
			log.Fatalf("Failed to hash admin password: %v", err)
		}

		// Generate unique referral code for admin
		refBytes := make([]byte, 4)
		if _, err := rand.Read(refBytes); err != nil {
			log.Fatalf("Failed to generate admin referral code: %v", err)
		}

		adminUser := models.User{
			Name:         "Admin",
			Email:        "admin",
			Phone:        "admin",
			Password:     string(hashedPassword),
			Role:         "admin",
			IsVerified:   true,
			ReferralCode: "ADMIN-" + hex.EncodeToString(refBytes),
		}

		if err := db.Create(&adminUser).Error; err != nil {
			slog.Error("Failed to create admin user", "error", err)
		} else if autoGenerated {
			slog.Warn("Default admin user created with auto-generated password. Set ADMIN_PASSWORD env var and redeploy to use a known password.")
		} else {
			slog.Info("Default admin user created with password from ADMIN_PASSWORD env var")
		}
	} else if adminPassword != "" {
		// Update existing admin password if ADMIN_PASSWORD env var is set
		hashedPassword, err := bcrypt.GenerateFromPassword([]byte(adminPassword), bcrypt.DefaultCost)
		if err != nil {
			slog.Error("Failed to hash admin password for update", "error", err)
		} else {
			db.Model(&models.User{}).Where("role = ? AND email = ?", "admin", "admin").Update("password", string(hashedPassword))
			slog.Info("Admin password updated from ADMIN_PASSWORD env var")
		}
	}

	// Create sample stores if none exist
	var count int64
	db.Model(&models.Store{}).Count(&count)
	if count == 0 {
		stores := []models.Store{
			{
				Name:       "McDonald's Balingasag",
				Category:   "restaurant",
				Latitude:   8.4343,
				Longitude:  124.5000,
				Address:    "Main St, Balingasag",
				Phone:      "+63912345678",
				Description: "Fast food restaurant",
				IsVerified: true,
				Rating:     4.5,
			},
			{
				Name:       "SM Grocery",
				Category:   "grocery",
				Latitude:   8.4340,
				Longitude:  124.4995,
				Address:    "Plaza St, Balingasag",
				Phone:      "+63912345679",
				Description: "Grocery store",
				IsVerified: true,
				Rating:     4.7,
			},
			{
				Name:       "Pharmacy Plus",
				Category:   "pharmacy",
				Latitude:   8.4345,
				Longitude:  124.5005,
				Address:    "Medical Ave, Balingasag",
				Phone:      "+63912345680",
				Description: "Medicine and health products",
				IsVerified: true,
				Rating:     4.8,
			},
		}

		for _, store := range stores {
			if err := db.Create(&store).Error; err != nil {
				slog.Error("Failed to create sample store", "store", store.Name, "error", err)
			}
		}
		slog.Info("Sample stores created")
	}

	// Create sample promos if none exist
	db.Model(&models.Promo{}).Count(&count)
	if count == 0 {
		promos := []models.Promo{
			{
				Code:           "WELCOME50",
				Description:    "50% off on first ride",
				DiscountType:   "percentage",
				DiscountValue:  50,
				MinimumAmount:  100,
				MaxDiscount:    500,
				UsageLimit:     1000,
				ApplicableTo:   "rides",
				IsActive:       true,
			},
			{
				Code:           "DELIVERY2024",
				Description:    "Free delivery on orders above 500",
				DiscountType:   "fixed",
				DiscountValue:  0,
				MinimumAmount:  500,
				UsageLimit:     5000,
				ApplicableTo:   "orders",
				IsActive:       true,
			},
		}

		for _, promo := range promos {
			if err := db.Create(&promo).Error; err != nil {
				slog.Error("Failed to create sample promo", "promo", promo.Code, "error", err)
			}
		}
		slog.Info("Sample promos created")
	}

	// Seed default commission config if none exists
	var commissionCount int64
	db.Model(&models.CommissionConfig{}).Count(&commissionCount)
	if commissionCount == 0 {
		defaultCommission := models.CommissionConfig{
			Percentage: 10.0,
			IsActive:   true,
		}
		if err := db.Create(&defaultCommission).Error; err != nil {
			slog.Error("Failed to create default commission config", "error", err)
		} else {
			slog.Info("Default commission config created", "percentage", 10.0)
		}
	}
}

func GetDB() *gorm.DB {
	return DB
}
